App/urls.py
from django.urls import path
from App.views import *

urlpatterns = [
    path("",LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("dashboard/",HomeView.as_view(),name="dashboard"),
    path("add-information",AddInformationView.as_view(),name="add-information"),
    path("delete-user/<int:id>/", DeleteUser.as_view(), name="delete-user"),
    path("edit-notify/<int:id>/", EditNotifyView.as_view(), name="edit-notify"),
    path("cron-job/", CronJobAPI.as_view(), name="cron-job"),
    path("email-management/", EmailView.as_view(), name="email-management"),
    path("add-email/", AddEmailView.as_view(), name="add-email"),
    path("edit-email/<int:id>/", EditEmailView.as_view(), name="edit-email"),
    path("delete-email/<int:id>/", DeleteEmailView.as_view(), name="delete-email"),
]

email_notify/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path("",include(("App.urls", "Admin"), namespace="Admin")),

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                
            </div>
          </div>
          <div class="col-xl-6">
            
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a href="https://appseed.us/admin-dashboards/django" 
                 class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://bit.ly/3fKQZaL" 
                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> 
                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </footer>

templates/includes/navigation-fullscreen.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title ">Login Page</title>

  <!-- Include Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  {% comment %} <nav id="navbar-main" style="background-color: #16749c" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="/">
                <img src="/static/assets/img/brand/book1.png">  </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="{% url 'Admin:login' %}" class="nav-link">
              <span class="nav-link-inner--text" style="color:#fff">Login</span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'Admin:signup' %}" class="nav-link">
              <span class="nav-link-inner--text" style="color:#fff">Register</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav> {% endcomment %}

  <!-- Include Bootstrap JS and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark  border-bottom" style="background-color: #1C93B6;height: 57px;">
  <div class="container-fluid" style="display: flex; justify-content: end;">
     


        
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark test" data-action="sidenav-pin" data-target="#sidenav-main" >
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        
  </div>
</nav>

<script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>


  <style>
    @media (min-width: 1190px) {
      .sidenav-toggler {
        display: none !important;
      }
    }

  </style>
  

templates/includes/scripts.html
{% comment %} {% extends 'layouts/base.html' %}

{% block title %} Dashboard {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
  .toggle-button {
    flex-grow: 1;
    text-align: center;
  }
  .toggle-button.is-active {
    background-color: #ccc;
  }
</style>
{% endblock stylesheets %}

{% block content %}

    <!-- Header -->
    <div class="header pb-6" style="background-color:#ffffff">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-black d-inline-block mb-0">View User - General View</h6>
            </div>
          </div>
          <!-- Card stats -->

          <!-- Toggle buttons -->
          <div class="d-flex justify-content-between mb-4">
            <button class="btn toggle-button" data-target="#general-info" style="background-color: #1c93b6; color: white; border-color: #1c93b6;">General Information</button>
            <button class="btn toggle-button" data-target="#user-goal-list" style="background-color: white; color: #1c93b6; border-color: #1c93b6;">User Goal List</button>
            <button class="btn toggle-button" data-target="#subscription-plan" style="background-color: white; color: #1c93b6; border-color: #1c93b6;">Subscription Plan</button>
            
          </div>


        <!-- Content -->
<div id="general-info" class="card text-center">
  <div class="card-body">
    <h5 class="card-title">General Information</h5>
    <p class="card-text">
      Name: Aadya Srivastava<br>
      Email Address: aadya@mailinator.com<br>
      Mobile Number: 1234567890<br>
      Age: 20<br>
      Gender: Female<br>
      Family Status: Married<br>
      Rewards Earned: 200 Points<br>
      Active Subscription Plan: Basic
    </p>
    <div class="border-bottom mb-3"></div>
  </div>
</div>

<div id="user-goal-list" class="card text-center" style="display: none;">
  <div class="card-body">
    <h5 class="card-title">User Goal List</h5>
    <p class="card-text">Content for User Goal List goes here.</p>
    <div class="border-bottom mb-3"></div>
  </div>
</div>

<div id="subscription-plan" class="card text-center" style="display: none;">
  <div class="card-body">
    <h5 class="card-title">Subscription Plan</h5>
    <p class="card-text">Content for Subscription Plan goes here.</p>
    <div class="border-bottom mb-3"></div>
  </div>
</div>

<div class="text-center">
  <button class="btn btn-primary" style="background-color: #1c93b6;border-color: #1c93b6" onclick="history.back()">Back</button>
</div>


        </div>
      </div>
    </div>
    <!-- Page content -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $(document).ready(function() {
        // Get the active button from localStorage
        var activeButton = localStorage.getItem('activeButton');
        if (activeButton) {
          $('.toggle-button').each(function() {
            if ($(this).data('target') === activeButton) {
              $(this).addClass('is-active').css('background-color', '#1c93b6').css('color', 'white');
              $($(this).data('target')).show();
            } else {
              $(this).removeClass('is-active').css('background-color', 'white').css('color', '#1c93b6');
              $($(this).data('target')).hide();
            }
          });
        }
    
        $('.toggle-button').click(function() {
          var target = $(this).data('target');
          $('.card').hide();
          $(target).show();
          $('.toggle-button').removeClass('is-active').css('background-color', 'white').css('color', '#1c93b6');
          $(this).addClass('is-active').css('background-color', '#1c93b6').css('color', 'white');
          
          // Store the active button in localStorage
          localStorage.setItem('activeButton', target);
        });
      });
    </script>
    
    

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="/static/assets/vendor/chart.js/dist/Chart.min.js"></script>
  <script src="/static/assets/vendor/chart.js/dist/Chart.extension.js"></script>

{% endblock javascripts %}













 {% endcomment %}

templates/includes/sidenav.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.2/dist/sweetalert2.min.css">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.2/dist/sweetalert2.all.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">

  <style>
    /* Your existing styles */

    /* Additional styles for responsive menu */
    @media (max-width: 991px) {
      .navbar-toggler {
        color: #fff;
        border: none;
        background-color: transparent;
      }

      .navbar-toggler:focus {
        outline: none;
      }

      #sidenav-main.collapsed {
        width: 60px;
      }

      #sidenav-main.collapsed .nav-link-text {
        display: none;
      }

      #sidenav-main.collapsed .navbar-brand,
      #sidenav-main.collapsed .navbar-toggler-icon {
        display: block;
      }
    }

    .nav-item {
      border: none;
      transition: background-color 0.3s;
    }

    .nav-item:hover {
      background-color: #1B87B5; /* Change background color on hover */
    }

    .nav-item.is_active {
      background-color: #16749c; /* Change active item color to green */
      border: none; /* Remove the border from active item */
    }

    .nav-item:not(.is_active) + .nav-item {
      border-top: 1px solid #1B87B5; /* Add border to all <li> elements except the first one */
    }
    
  </style>


  <script>
    $(document).ready(function() {
      // Get all the navigation items (list items)
      const navItems = $('.nav-item');

      // Add a click event listener to each navigation item
      navItems.click(function() {
        // Remove the 'is_active' class from all navigation items
        navItems.removeClass('is_active');
        // Add the 'is_active' class to the clicked navigation item
        $(this).addClass('is_active');
      });
    });

    function showLogoutConfirmation() {
      Swal.fire({
        text: 'Are you sure you want to logout?',
        iconHtml: '<div class="icon-shape bg-danger text-gray rounded-circle shadow-none fa-xs"><i class="fas fa-sign-out-alt"></i></div>', // Replace with the appropriate icon HTML
        showCancelButton: true,
        showCloseButton: true,
        confirmButtonText: 'Yes',
        cancelButtonText: 'No',
        customClass: {
          icon: 'material-icons-outlined',
        },
      }).then((result) => {
        if (result.isConfirmed) {
          // Perform logout action
          window.location.href = '/logout'; // Replace with your logout URL
        }
      });
    }
  </script>



</head>
<body>
  <nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs bg-black" id="sidenav-main" style="background-color: #1c93b6; border:none">
   
    <div class="scrollbar-inner">
      
      <!-- Brand -->
      <div class="sidenav-header align-items-center">
        <a class="navbar-brand" href="/" style="color: #fff">
          {% comment %} <img src="/static/assets/img/brand/blue.png" class="navbar-brand-img" alt="Logo Design - Jinja Template Logo."> {% endcomment %}
          {% comment %} <img src="/static/assets/img/brand/book1.png">  </a> {% endcomment %}
        </a>
        {% comment %} <h3 style="color: #fff">Atomic Journal</h3> {% endcomment %}
        {% comment %} <h4 style="color: #fff">mobiloitte@gmail.com</h4> {% endcomment %}
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
           
            </li>
            <li class="nav-item {% if 'user' in request.path %} is_active {% endif %}">
              <a style="color: #fff" class="nav-link" href="{% url 'Admin:dashboard' %}">
                <i class="ni ni-planet  text-white"></i>
                <span class="nav-link-text">User Management</span>
              </a>
            </li>
            
            <li class="nav-item {% if 'user' in request.path %} is_active {% endif %}">
              <a style="color: #fff" class="nav-link" href="{% url 'Admin:email-management' %}">
                <i class="ni ni-planet  text-white"></i>
                <span class="nav-link-text">Email Management</span>
              </a>
            </li>
            
            <li class="nav-item {% if 'user' in request.path %} is_active {% endif %}">
              <a style="color: #fff" class="nav-link" href="{% url 'Admin:logout' %}">
                <i class="ni ni-planet  text-white"></i>
                <span class="nav-link-text">Logout</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</body>
</html>