App/urls.py
from django.urls import path
from App.views import *

urlpatterns = [
    path("",LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("dashboard/",HomeView.as_view(),name="dashboard"),
    path("add-information",AddInformationView.as_view(),name="add-information"),
    path("delete-user/<int:id>/", DeleteUser.as_view(), name="delete-user"),
    path("edit-notify/<int:id>/", EditNotifyView.as_view(), name="edit-notify"),
    path("cron-job/", CronJobAPI.as_view(), name="cron-job"),
    path("email-management/", EmailView.as_view(), name="email-management"),
    path("add-email/", AddEmailView.as_view(), name="add-email"),
    path("edit-email/<int:id>/", EditEmailView.as_view(), name="edit-email"),
    path("delete-email/<int:id>/", DeleteEmailView.as_view(), name="delete-email"),
]

email_notify/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path("",include(("App.urls", "Admin"), namespace="Admin")),

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/add-email.html
{% extends 'layouts/base.html' %} {% block title %} Tables {% endblock title %}
{% block content %}

<div class="header pb-6 mt-4" style="background-color: #ffffff">
  <div class="container-fluid">
    <h2 class="mb-0">Add User</h2>
    <div class="header-body"></div>
    <form method="post">   
      {% csrf_token %}
      <div class="row mt-5">
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols1Input">Employee Name</label>
            <input
              type="text"
              class="form-control"
              id="example3cols1Input"
              placeholder="Employee Name"
              name="emp_name"
            />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols2Input"
              >Email Address</label
            >
            <input
              type="email"
              class="form-control"
              id="example3cols2Input"
              placeholder="Email Address"
              name="email_address"
            />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <div class="form-group">
              <label for="exampleFormControlSelect1">Expires</label>
              <input
              type="text"
              class="form-control"
              id="example3cols2Input"
              placeholder="Expires"
              name="expires"
            />
          </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Password</label>
            <input
              type="password"
              class="form-control"
              id=""
              placeholder=""
              name="password"
            />
          </div>
        </div>
      </div>
     
 

    <div class="d-flex justify-content-center">
     <button style="background-color:#1c93b6; color:#fff; border:#1c93b6" type="submit" class="btn btn-outline-success">Add</button>
     <button  onclick="history.back()" style="background-color:#1c93b6; color:#fff; border:#1c93b6" type="button" class="btn btn-outline-success">Back</button>

    </div>
  </form>
  </div>

  <style>
    input[type="text"],
    input[type="email"],
    select {
      border-color: #525f7f !important;
    }
  </style>
  <script>
    document.getElementById('example3cols3Input').addEventListener('input', function (e) {
      const input = e.target;
      const value = input.value;
      const regex = /^\d{4}-\d{2}-\d{2}$/;
  
      if (!regex.test(value)) {
        input.setCustomValidity('Please enter the date in the format YYYY-MM-DD');
      } else {
        input.setCustomValidity('');
      }
    });
  </script>
  

  {% endblock content %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}
</div>

templates/add-user.html
{% extends 'layouts/base.html' %} {% block title %} Tables {% endblock title %}
{% block content %}

<div class="header pb-6 mt-4" style="background-color: #ffffff">
  <div class="container-fluid">
    <h2 class="mb-0">Add User</h2>
    <div class="header-body"></div>
    <form method="post">   
      {% csrf_token %}
      <div class="row mt-5">
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols1Input">Domain Name</label>
            <input
              type="text"
              class="form-control"
              id="example3cols1Input"
              placeholder="domain_name"
              name="domain_name"
            />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols2Input"
              >Server IP</label
            >
            <input
              type="text"
              class="form-control"
              id="example3cols2Input"
              placeholder="server_ip"
              name="server_ip"
            />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Associated Account</label>
            <input
              type="text"
              class="form-control"
              id=""
              placeholder="associated_account"
              name="associated_account"
            />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Customer ID</label>
            <input
              type="text"
              class="form-control"
              id=""
              placeholder="customer_id"
              name="customer_id"
            />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Domain - Account</label>
            <input
              type="text"
              class="form-control"
              id=""
              placeholder="domain_account"
              name="domain_account"
            />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">SSL Status</label>
            <input
              type="text"
              class="form-control"
              id=""
              placeholder="ssl_status"
              name="ssl_status"
            />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Hosted Account</label>
            <input
              type="text"
              class="form-control"
              id=""
              placeholder="hosted_account"
              name="hosted_account"
            />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Remark</label>
            <input
              type="text"
              class="form-control"
              id=""
              placeholder="remark"
              name="remark"
            />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Expires</label>
            <input
              type="text"
              class="form-control"
              id="example3cols3Input"
              placeholder="YYYY-MM-DD"
              name="expires"
              pattern="\d{4}-\d{2}-\d{2}"
              title="Please enter the date in the format YYYY-MM-DD"
            />
          </div>
        </div>
      </div>
 

    <div class="d-flex justify-content-center">
     <button style="background-color:#1c93b6; color:#fff; border:#1c93b6" type="submit" class="btn btn-outline-success">Add</button>
     <button  onclick="history.back()" style="background-color:#1c93b6; color:#fff; border:#1c93b6" type="button" class="btn btn-outline-success">Back</button>

    </div>
  </form>
  </div>

  <style>
    input[type="text"],
    input[type="email"],
    select {
      border-color: #525f7f !important;
    }
  </style>
  <script>
    document.getElementById('example3cols3Input').addEventListener('input', function (e) {
      const input = e.target;
      const value = input.value;
      const regex = /^\d{4}-\d{2}-\d{2}$/;
  
      if (!regex.test(value)) {
        input.setCustomValidity('Please enter the date in the format YYYY-MM-DD');
      } else {
        input.setCustomValidity('');
      }
    });
  </script>
  

  {% endblock content %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}
</div>

templates/edit-email.html
{% extends 'layouts/base.html' %} {% block title %} Tables {% endblock title %}
{% block content %}

<div class="header pb-6 mt-4" style="background-color: #ffffff">
  <div class="container-fluid">
    <h2 class="mb-0">Add User</h2>
    <div class="header-body"></div>
    <form method="post">   
      {% csrf_token %}
      <div class="row mt-5">
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols1Input">Employee Name</label>
            <input
              type="text"
              class="form-control"
              id="example3cols1Input"
              placeholder="Employee Name"
              name="emp_name"
              value="{{edit_obj.emp_name}}"
            />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols2Input"
              >Email Address</label
            >
            <input
              type="email"
              class="form-control"
              id="example3cols2Input"
              placeholder="Email Address"
              name="email_address"
              value="{{edit_obj.email_address}}"
            />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            
            <label for="exampleFormControlSelect1">Expires</label>
              <input
              type="text"
              class="form-control"
              id="example3cols2Input"
              placeholder="Expires"
              name="expires"
              value="{{edit_obj.expires}}"
            />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="form-control-label" for="example3cols3Input">Password</label>
            <input
              type="text"
              class="form-control"
              id=""
              placeholder="Password"
              name="password"
              value="{{edit_obj.password}}"
            />
          </div>
        </div>
      </div>
     
 

    <div class="d-flex justify-content-center">
     <button style="background-color:#1c93b6; color:#fff; border:#1c93b6" type="submit" class="btn btn-outline-success">Add</button>
     <button  onclick="history.back()" style="background-color:#1c93b6; color:#fff; border:#1c93b6" type="button" class="btn btn-outline-success">Back</button>

    </div>
  </form>
  </div>

  <style>
    input[type="text"],
    input[type="email"],
    select {
      border-color: #525f7f !important;
    }
  </style>
  <script>
    document.getElementById('example3cols3Input').addEventListener('input', function (e) {
      const input = e.target;
      const value = input.value;
      const regex = /^\d{4}-\d{2}-\d{2}$/;
  
      if (!regex.test(value)) {
        input.setCustomValidity('Please enter the date in the format YYYY-MM-DD');
      } else {
        input.setCustomValidity('');
      }
    });
  </script>
  

  {% endblock content %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}
</div>

templates/email-management.html
{% extends 'layouts/base.html' %}

{% block title %}Tables{% endblock title %}

{% block content %}

<div class="header pb-6 mt-4" style="background-color:#ffffff">
  <div class="container-fluid">
      <h2 class="mb-0">Email Management</h2>
    
      <div class="header-body mt-5" style="box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;">
        <div class="row align-items-center py-4" style="display: flex; justify-content: end; padding: 6px;">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <div class="col-lg-6">
                    <input type="file" class="form-control" id="customFile" name="file" />
                </div>
                <div class="col-lg-2">
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
                <div class="col-lg-4">
                    <a href="{% url 'Admin:add-email' %}" class="btn" style="background-color:#898989; color: #fff">Add Email</a>
                </div>
            </div>
        </form>
        </div>
      </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--5">
  <div class="row">
    <div class="col">
      <div class="card">
        <!-- Card header -->
        
        <!-- Light table -->
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="text-center" style="background-color:#1c93b6; color:#fff">
              <tr>
                <th scope="col" class="sort" data-sort="name">SN</th>
                <th scope="col" class="sort" data-sort="budget">Employee Name</th>
                <th scope="col" class="sort" data-sort="status">Email Address</th>
                <th scope="col">Expires</th>
                <th scope="col" class="sort" data-sort="completion">Password</th>
                <th scope="col" class="sort" data-sort="completion">Action</th>
              </tr>
            </thead>
            
            <tbody class="list text-center">
              {% for i in email_data %}
                <tr class="{% if i.expires and i.expires >= today %}expired{% endif %}">
                  <th scope="row">
                    <div class="media align-items-center">
                      <div class="media-body">
                        <span class="name mb-0 text-sm">{{ forloop.counter }}</span>
                      </div>
                    </div>
                  </th>
                  <td class="budget">
                    {{ i.emp_name }}
                  </td>
                  <td>
                    {{ i.email_address }}
                  </td>
                  <td>
                    <div class="avatar-group">
                      {{ i.expires }}
                    </div>
                  </td>
                  <td>
                    {{ i.password }}
                  </td>
                  <td>
                    <div class="align-items-center">
                      <a href="{% url 'Admin:edit-email' i.id %}" class="btn btn-sm btn-success">Edit</a>
                      <button class="btn btn-sm btn-success" onclick="showDeleteUserConfirmations('{{ i.id }}')">Delete</button>
                    </div>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- Card footer -->
        <div class="card-footer py-4">
          <nav aria-label="...">
            <ul class="pagination justify-content-end mb-0">
              {% if user_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-double-left"></i>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ user_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-left"></i>
                  </a>
                </li>
              {% endif %}
        
              {% for page_number in user_obj.paginator.page_range %}
                <li class="page-item {% if user_obj.number == page_number %}active{% endif %}">
                  <a class="page-link" href="?page={{ page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    {{ page_number }}
                  </a>
                </li>
              {% endfor %}
        
              {% if user_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ user_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-right"></i>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ user_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-double-right"></i>
                  </a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function showDeleteUserConfirmations(userId) {
      Swal.fire({
          text: 'Are you sure you want to delete this user?',
          iconHtml: '<div class="icon-shape bg-danger text-gray rounded-circle shadow-none fa-xs" style="padding: 10px;"><i class="fas fa-trash"></i></div>',
          showCancelButton: true,
          showCloseButton: true,
          confirmButtonText: 'Yes',
          cancelButtonText: 'No',
          customClass: {
              icon: 'material-icons-outlined',
          },
      }).then((result) => {
          if (result.isConfirmed) {
              
              window.location.href = `/delete-email/${userId}/`; 
          }
      });
  }

  // Function to convert a table to CSV format
  function convertTableToCSV(table) {
    const rows = Array.from(table.getElementsByTagName('tr'));
    const headers = Array.from(rows[0].getElementsByTagName('th'));

    return rows.map(row => {
      const columns = Array.from(row.getElementsByTagName('td'));
      return headers
        .filter(header => header.textContent.trim() !== 'Action') // Exclude Action column
        .concat(columns)
        .map(column => column.textContent.trim().replace(/View|Edit|Delete|Action/g, '')) // Trim and replace specified values
        .join(',');
    }).join('\n');
  }

  // Function to trigger the CSV download
  function downloadCSV(csvContent, fileName) {
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = fileName;
    link.click();
  }

  // Add click event listener to the download button
  document.getElementById('download-btn').addEventListener('click', function () {
    const table = document.querySelector('.table-responsive table');
    const csvContent = convertTableToCSV(table);
    const fileName = 'table_data.csv';
    downloadCSV(csvContent, fileName);
  });
</script>

<style>
  .expired {
    background-color: red;
    color: white;  /* Optional: To make text readable */
  }

  .btn-success {
    color: #fff;
    background-color: #1c93b6;
    border-color: #1c93b6;
    box-shadow: 0 4px 6px rgba(50, 50, 93, 0.11), 0 1px 3px rgba(0, 0, 0, 0.08);
  }

  .btn-outline-success {
    color: #1C93B6;
    background-color: transparent;
    background-image: none;
    border-color: #1C93B6;
  }

  .btn-success:hover {
    color: #fff;
    background-color: #1C93B6;
    border-color: #1C93B6;
  }

  .btn-outline-success:hover {
    background-color: #1C93B6;
    color: #fff;
    border-color: #1C93B6;
  }

  .page-item.active .page-link {
    z-index: 3;
    color: #fff;
    background-color: #1C93B6;
    border-color: #1C93B6;
  }

  input[type="date"]::-webkit-calendar-picker-indicator {
    filter: invert(1); /* Change the icon color to white */
  }
</style>

{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/user-management.html
{% extends 'layouts/base.html' %}

{% block title %}Tables{% endblock title %}

{% block content %}

<div class="header pb-6 mt-4" style="background-color:#ffffff">
  <div class="container-fluid">
      <h2 class="mb-0">User Management</h2>
    
    <div class="header-body mt-5" style="box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;">
      <div class="row align-items-center py-4" style="display: flex; justify-content: end; padding: 6px;">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group row">
              <div class="col-lg-6">
                  <input type="file" class="form-control" id="customFile" name="file" />
              </div>
              <div class="col-lg-2">
                  <button type="submit" class="btn btn-primary">Upload</button>
              </div>
              <div class="col-lg-4">
                  <a href="{% url 'Admin:add-information' %}" class="btn" style="background-color:#898989; color: #fff">Add Information</a>
              </div>
          </div>
      </form>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--5">
  <div class="row">
    <div class="col">
      <div class="card">
        <!-- Card header -->
        
        <!-- Light table -->
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="text-center" style="background-color:#1c93b6; color:#fff">
              <tr>
                <th scope="col" class="sort" data-sort="name">SN</th>
                <th scope="col" class="sort" data-sort="budget">Domain Name</th>
                {% comment %} <th scope="col" class="sort" data-sort="status">Server IP</th>
                <th scope="col">Associated Account</th>
                <th scope="col" class="sort" data-sort="completion">Customer ID</th>
                <th scope="col">Domain - Account</th>
                <th scope="col">SSL Status</th>
                <th scope="col">Hosted Account</th>
                <th scope="col">Remark</th> {% endcomment %}
                <th scope="col">Expires</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            
            <tbody class="list text-center">
              {% for i in notify_obj %}
                <tr class="{% if i.expires <= today %}expired{% endif %}" onclick="window.location.href='{% url 'Admin:edit-notify' i.id %}'" style="cursor: pointer;">
                  <th scope="row">
                    <div class="media align-items-center">
                      <div class="media-body">
                        <span class="name mb-0 text-sm">{{ forloop.counter }}</span>
                      </div>
                    </div>
                  </th>
                  <td class="budget">
                    {{ i.domain_name }}
                  </td>
                  {% comment %} 
                  <!-- Other commented-out columns -->
                  {% endcomment %}
                  <td>
                    {{ i.expires }}
                  </td>
                  <td>
                    <div class="align-items-center">
                      <a href="{% url 'Admin:edit-notify' i.id %}" class="btn btn-sm btn-success">Edit</a>
                      <button class="btn btn-sm btn-success" onclick="showDeleteUserConfirmation('{{ i.id }}')">Delete</button>
                    </div>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
            
          </table>
        </div>
        <!-- Card footer -->
        <div class="card-footer py-4">
          <nav aria-label="...">
            <ul class="pagination justify-content-end mb-0">
              {% if user_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-double-left"></i>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ user_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-left"></i>
                  </a>
                </li>
              {% endif %}
        
              {% for page_number in user_obj.paginator.page_range %}
                <li class="page-item {% if user_obj.number == page_number %}active{% endif %}">
                  <a class="page-link" href="?page={{ page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    {{ page_number }}
                  </a>
                </li>
              {% endfor %}
        
              {% if user_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ user_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-right"></i>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ user_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}">
                    <i class="fas fa-angle-double-right"></i>
                  </a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function showDeleteUserConfirmation(userId) {
      Swal.fire({
          text: 'Are you sure you want to delete this user?',
          iconHtml: '<div class="icon-shape bg-danger text-gray rounded-circle shadow-none fa-xs" style="padding: 10px;"><i class="fas fa-trash"></i></div>',
          showCancelButton: true,
          showCloseButton: true,
          confirmButtonText: 'Yes',
          cancelButtonText: 'No',
          customClass: {
              icon: 'material-icons-outlined',
          },
      }).then((result) => {
          if (result.isConfirmed) {
              
              window.location.href = `/delete-user/${userId}/`; 
          }
      });
  }

  // Function to convert a table to CSV format
  function convertTableToCSV(table) {
    const rows = Array.from(table.getElementsByTagName('tr'));
    const headers = Array.from(rows[0].getElementsByTagName('th'));

    return rows.map(row => {
      const columns = Array.from(row.getElementsByTagName('td'));
      return headers
        .filter(header => header.textContent.trim() !== 'Action') // Exclude Action column
        .concat(columns)
        .map(column => column.textContent.trim().replace(/View|Edit|Delete|Action/g, '')) // Trim and replace specified values
        .join(',');
    }).join('\n');
  }

  // Function to trigger the CSV download
  function downloadCSV(csvContent, fileName) {
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = fileName;
    link.click();
  }

  // Add click event listener to the download button
  document.getElementById('download-btn').addEventListener('click', function () {
    const table = document.querySelector('.table-responsive table');
    const csvContent = convertTableToCSV(table);
    const fileName = 'table_data.csv';
    downloadCSV(csvContent, fileName);
  });
</script>

<style>
  .expired {
    background-color: red;
    color: white;  /* Optional: To make text readable */
  }

  .btn-success {
    color: #fff;
    background-color: #1c93b6;
    border-color: #1c93b6;
    box-shadow: 0 4px 6px rgba(50, 50, 93, 0.11), 0 1px 3px rgba(0, 0, 0, 0.08);
  }

  .btn-outline-success {
    color: #1C93B6;
    background-color: transparent;
    background-image: none;
    border-color: #1C93B6;
  }

  .btn-success:hover {
    color: #fff;
    background-color: #1C93B6;
    border-color: #1C93B6;
  }

  .btn-outline-success:hover {
    background-color: #1C93B6;
    color: #fff;
    border-color: #1C93B6;
  }

  .page-item.active .page-link {
    z-index: 3;
    color: #fff;
    background-color: #1C93B6;
    border-color: #1C93B6;
  }

  input[type="date"]::-webkit-calendar-picker-indicator {
    filter: invert(1); /* Change the icon color to white */
  }
</style>

{% endblock content %}
{% block javascripts %}{% endblock javascripts %}